### ISSUE TITLE
BUG: parameter including_start is not correct

### ISSUE THREAD

**Issue by marcelkb** [eric-volz/DefichainPython#20]
**Describe the bug**
In der vault.py Klasse
ist bei der Methode
`  def listauctions(self, vaultId=None, height=None, including_start=False, limit=100):  # 09
`
including_start als Default False gesetzt wie es auch in der Dokumentation steht
`   "including_start": bool,    (boolean) If true, then iterate including starting position. False by default
` 
Es wird jedoch immer dort ein JSON zusammengebaut.
`DEBUG (MainThread) 21.05.2022 10:33:56 {"method": "listauctions", "params": [{"start": {}, "including_start": false, "limit": 100}], "jsonrpc": "2.0"}`

 Damit wird das Verhalten zum Standard Konsolenauruf von listauctions verändert und es kommt die erste Auktion nicht zurück.
 Wenn man jedoch keine expliziten Parameter der Funktion übergibt würde ich erwarten das diese erstmal alles zurückliefert.

**Comment by eric-volz** [comment]
### Dankeschön für den Report!

Dieser Bug hat sich sogar nicht nur auf die Funktion listauctions bezogen, sondern auf alle Methoden die den Parameter including_start beinhaltet haben:

#### Methoden die betroffen waren:
1. Masternodes:
a. listmasternodes
2. Oracles:
a. listlatestrawprices
b. listoracles
c. listprices
3. Poolpair:
a. listpoolpairs
b. listpoolshares
4. Token:
a. listtokens
5. Vault:
a. listauctions
b. listvaults

#### Für den Endnutzer sollte sich an der Verwendung der Library nichts verändert haben, außer das jetzt die Ausgaben der gezeigten oberen Methoden nicht mehr unvollständig sind!

[Link zum fix Commit](https://github.com/eric-volz/DefichainPython/commit/94c741aea4e6d69dfdd9e2ca9bad1a3e6474553e)

---

### Thank you for the report!

This bug was not only related to the listauctions function, but to all methods that contained the including_start parameter:

#### Methods that were affected:
Masternodes:
a. listmasternodes
Oracles:
a. listlatestrawprices
b. listoracles
c. listprices
Poolpairs:
a. listpoolpairs
b. listpoolshares
tokens:
a. listtokens
Vault:
a. listauctions
b. listvaults

#### For the end user nothing should have changed in the use of the library, except that now the outputs of the shown upper methods are no longer incomplete!

[Link to the fix commit](https://github.com/eric-volz/DefichainPython/commit/94c741aea4e6d69dfdd9e2ca9bad1a3e6474553e)
