### ISSUE TITLE
IMPROV: DEBUG Log RPC Call

### ISSUE THREAD

**Issue by marcelkb** [eric-volz/DefichainPython#56]
Right now it is not possible to double check what the pyhton api send,
It would be nice if in DEBUG Mode the Api logs what it sends over rpc.
f.e. in rpc.py:
  ```
if rpc_method == "walletpassphrase" or rpc_method == "signrawtransactionwithkey":
            logging.debug(json.dumps({"method": rpc_method, "params": '***',"jsonrpc": "2.0"}))
        else:
            logging.debug(payload)
```

so technic affine users can check what it really does.

**Comment by eric-volz** [comment]
Thanks for the idea, I'll add it as soon as possible! :)

**Comment by eric-volz** [comment]
Thanks again for the improvement suggestion.

Here is an example how to use the new logger:
```
from defichain import Ocean
from defichain.logger import Logger  # import Logger

logger = Logger(log_level="error")  # initialize logger with log level error
ocean = Ocean(logger=logger)  # pass logger to Ocean instance

ocean.address.getBalance("wrong_address")  # error will get logged
```
The use of the logger for the Node module works exactly the same way.

You can also give the logger a telegram token and a telegram chatid and the logs will be sent to you. 
This is especially useful in "error" mode, because you can quickly notice when your script is no longer working.

The [logger documentation](https://docs.defichain-python.de/build/html/api/logger.html) is also already available.

The PyPi release will follow in the next days.
